version: '3.4'

services:
  pipeline:
    build: .
    container_name: pipeline
    command: node ./build
    tty: true
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sportradar
      POSTGRES_PASSWORD: sportradar
      POSTGRES_DB: sportradar

volumes:
  postgres: